target_tracking_node:
  ros__parameters:
    topic_pointcloud_in: "lidar/centroids"
    topic_landmarks_out: "target_tracking/landmarks"
    topic_visualization_parameters: "target_tracking/parameters"
    clutter_rate: 0.001
    probability_of_detection: 0.7
    probability_of_survival: 0.99
    gate_threshold: 2.5
    min_gate_threshold: 1.0
    max_gate_threshold: 10.0
    confirmation_threshold: 0.9
    deletion_threshold: 0.2
    std_velocity: 0.2
    std_sensor: 0.5
    update_interval_ms: 500
    world_frame: "world_frame"
    publish_visualization: true