version: '3.8'
services:
  vortex:
    container_name: sift
    build: .
    image: sift:autolaunch
    user: vortex
    privileged: true
    volumes:
    #example: - ~/OneDrive/Documents:/home/vortex
      - "~/workshop2023/src:/home/workshop2023/src"
      - "/dev:/dev"

    environment:
      DISPLAY: :0
    stdin_open: true
    tty: true
    network_mode: host
    #entrypoint: ["/entrypoint.sh"]

