pcl_detector_node:
  ros__parameters:
    processor:
      voxel_leaf_size: 0.1
      model_thresh: 0.5
      model_iterations: 10
      prev_line_thresh: 0.5
      project_thresh: 0.5
      wall_min_dist: 1.0
      wall_min_points: 50
    
    transform_lines: true
    transform_timeout_nsec: 50000000
    prev_line_min_inliers: 50
    new_lines: 1
    

    detector: "dbscan" # one of "dbscan", "euclidean"
    
    dbscan:
      epsilon: 2.0
      min_points: 20

    euclidean:
      cluster_tolerance: 1.0
      min_points: 25